[tools]
# https://mise-tools.jdx.dev/tools/yq
yq = "4.53.2"
# https://mise-tools.jdx.dev/tools/lefthook
lefthook = "2.1.6"
# https://mise-tools.jdx.dev/tools/jsonschema
jsonschema = "15.2.0"
# https://mise-tools.jdx.dev/tools/golangci-lint
golangci-lint = "2.12.0"
