package mkcert

type Config struct {
	// Directory the generated certificates and keys are written to, relative to
	// the project root. Required by `generate` and `create`, which both refuse to
	// run when it is empty; created on demand if missing.
	CertificatePath string `json:"certificatePath" yaml:"certificatePath"`
	// Certificates generated by `generate`, one mkcert invocation each.
	Certificates []Certificate `json:"certificates" yaml:"certificates"`
}
