name: Test Branch

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: sourcemeta/jsonschema@v9.2.2

      #- uses: gotesttools/gotestfmt-action@v2
      #  with:
      #    token: ${{ secrets.GITHUB_TOKEN }}

      - uses: golangci/golangci-lint-action@v7
        with:
          version: latest

      - name: Run test
        run: make test

      - name: Generate schema
        run: |
          make schema
          git diff
          #git diff --exit-code

      - uses: coverallsapp/github-action@v2
        with:
          file: coverage.out

