name: Test Branch

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: jdx/mise-action@v3

      - uses: actions/setup-go@v6
        with:
          check-latest: true
          go-version-file: go.mod

      - uses: golangci/golangci-lint-action@v8
        with:
          install-mode: none

      - name: Run tidy
        run: make tidy && git diff --exit-code

      - name: Run lint
        run: make lint

      - name: Run test
        run: make test

      - name: Generate schema
        run: make schema & git diff --exit-code

